// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

import "@openzeppelin/contracts/utils/Context.sol";
import "@openzeppelin/contracts/utils/Counters.sol";
import "@openzeppelin/contracts/token/ERC1155/extensions/ERC1155Supply.sol";
import "../accesscontrol/interfaces/IFlowAccessControl.sol";

/**
 * @dev {ERC1155} token, including:
 *
 *  - ability for holders to burn (destroy) their tokens
 *  - a creator role that allows for token minting (creation)
 *  - token ID and URI autogeneration
 *
 * This contract uses {AccessControl} to lock permissioned functions using the
 * different roles - head to its documentation for details.
 *
 * The account that deploys the contract will be granted the creator and pauser
 * roles, as well as the default admin role, which will let it grant both creator
 * and pauser roles to other accounts.
 */

// collection URI override

contract FlowCollection is Context, ERC1155Supply {
    using Counters for Counters.Counter;

    Counters.Counter private _tokenIdTracker;

    // Optional mapping for token URIs
    mapping(uint256 => string) private _tokenURIs;

    address public marketplace;

    IFlowAccessControl flowRoles;

    modifier onlyOperator() {
        require(
            flowRoles.isOperator(_msgSender()),
            "FlowCollection: Unauthorized!"
        );
        _;
    }

    modifier onlyCreator() {
        require(
            flowRoles.isCreator(_msgSender()),
            "FlowCollection: Unauthorized!"
        );
        _;
    }

    event AssetCreated(
        uint256 indexed tokenID,
        address indexed creator,
        uint256 indexed amount
    );
    event AssetDestroyed(uint indexed tokenId, address ownerOrApproved);

    // marketplace should be there
    /**
     * @dev Grants `FLOW_ADMIN_ROLE`, `FLOW_CREATOR_ROLE` and `FLOW_OPERATOR_ROLE` to the
     * account that deploys the contract.
     *
     */
    constructor(
        string memory baseURI,
        address marketplaceAddress,
        address flowContract
    ) ERC1155(baseURI) {
        marketplace = marketplaceAddress;
        flowRoles = IFlowAccessControl(flowContract);
    }

    /**
     * @dev Creates a new token for `to`. Its token ID will be automatically
     * assigned (and available on the emitted {IERC721-Transfer} event), and the token
     * URI autogenerated based on the base URI passed at construction.
     *
     * See {ERC721-_safeMint}.
     *
     * Requirements:
     *
     * - the caller must have the `FLOW_CREATOR_ROLE`.
     */
    function createAsset(
        uint256 amount,
        bytes memory data,
        string memory _uri
    ) public onlyCreator returns (uint256) {
        // We cannot just use balanceOf to create the new tokenId because tokens
        // can be burned (destroyed), so we need a separate counter.
        _tokenIdTracker.increment();
        uint256 currentTokenID = _tokenIdTracker.current();
        _mint(_msgSender(), currentTokenID, amount, data);
        _tokenURIs[currentTokenID] = _uri;
        setApprovalForAll(marketplace, true);
        emit AssetCreated(currentTokenID, _msgSender(), amount);
        return currentTokenID;
    }

    /**
     * @dev Creates a new token for `to`. Its token ID will be automatically
     * assigned (and available on the emitted {IERC721-Transfer} event), and the token
     * URI autogenerated based on the base URI passed at construction.
     *
     * See {ERC721-_safeMint}.
     *
     * Requirements:
     *
     * - the caller must have the `FLOW_CREATOR_ROLE`.
     */
    function delegateAssetCreation(
        address creator,
        uint256 amount,
        bytes memory data,
        string memory _uri
    ) public onlyOperator returns (uint256) {
        // We cannot just use balanceOf to create the new tokenId because tokens
        // can be burned (destroyed), so we need a separate counter.
        _tokenIdTracker.increment();
        uint256 currentTokenID = _tokenIdTracker.current();
        _mint(creator, currentTokenID, amount, data);
        _tokenURIs[currentTokenID] = _uri;
        setApprovalForAll(marketplace, true);
        emit AssetCreated(currentTokenID, _msgSender(), amount);
        return currentTokenID;
    }

    function destroyAsset(uint256 tokenId, uint256 amount) public {
        require(
            balanceOf(_msgSender(), tokenId) == amount,
            "FlowCollection: Caller is not token owner or approved"
        );
        _burn(_msgSender(), tokenId, amount);
        emit AssetDestroyed(tokenId, _msgSender());
    }

    function uri(
        uint256 tokenId
    ) public view virtual override returns (string memory) {
        return _tokenURIs[tokenId];
    }

    // ONLY Operator can change Base URI
    function setURI(string memory newuri) external onlyOperator {
        _setURI(newuri);
    }

    function _beforeTokenTransfer(
        address operator,
        address from,
        address to,
        uint256[] memory ids,
        uint256[] memory amounts,
        bytes memory data
    ) internal virtual override(ERC1155Supply) {
        super._beforeTokenTransfer(operator, from, to, ids, amounts, data);
    }

    //uri ovverrride -> tokenID URI

    /**
     * @dev See {IERC165-supportsInterface}.
     */
    function supportsInterface(
        bytes4 interfaceId
    ) public view virtual override(ERC1155) returns (bool) {
        return super.supportsInterface(interfaceId);
    }
}
