// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

import "@openzeppelin/contracts/utils/Context.sol";
import "@openzeppelin/contracts/token/ERC1155/extensions/ERC1155Supply.sol";
import "../accessmaster/interfaces/IAccessMaster.sol";

contract RewardToken is Context, ERC1155Supply {
    string public name;
    string public symbol;

    address public tradeHub;
    address public accessMasterAddress;

    uint256 public Counter;
    uint8 public constant version = 1;
    // Optional mapping for token URIs
    mapping(uint256 => string) private _tokenURIs;
    mapping(address => mapping(uint256 => uint256)) public phygitalToRewardId;

    //// phygitalTokenID  => RewardToken -- >if it exists +++

    IACCESSMASTER flowRoles;

    modifier onlyOperator() {
        require(
            flowRoles.isOperator(_msgSender()),
            "RewardToken: Unauthorized!"
        );
        _;
    }

    modifier onlyCreator() {
        require(
            flowRoles.isCreator(_msgSender()),
            "RewardToken: Unauthorized!"
        );
        _;
    }

    event RewardTokenCreated(
        uint256 indexed tokenID,
        address indexed creator,
        uint256 indexed amount,
        string metadataUri
    );
    event RewardTokenDestroyed(uint indexed tokenId, address ownerOrApproved);

    // tradeHub should be there
    /**
     * @dev Grants `FLOW_ADMIN_ROLE`, `FLOW_CREATOR_ROLE` and `FLOW_OPERATOR_ROLE` to the
     * account that deploys the contract.
     *
     */
    constructor(
        string memory baseURI,
        string memory _name,
        string memory _symbol,
        address tradeHubAddress,
        address flowContract
    ) ERC1155(baseURI) {
        name = _name;
        symbol = _symbol;
        tradeHub = tradeHubAddress;
        flowRoles = IACCESSMASTER(flowContract);
        accessMasterAddress = flowContract;
    }

    /**
     * @dev Creates a new token for `to`. Its token ID will be automatically
     * assigned (and available on the emitted {IERC1155-Transfer} event), and the token
     * URI autogenerated based on the base URI passed at construction.
     *
     *
     * Requirements:
     *
     * - the caller must have the `FLOW_CREATOR_ROLE`.
     */
    ///IssueRewardToken
    function createFanToken(
        address phygitalcontractAddr,
        uint256 amount,
        uint256 tokenId,
        bytes memory data,
        string memory _uri
    ) public returns (uint256) {
        uint256 currentTokenID;
        if (phygitalToRewardId[phygitalcontractAddr][tokenId] > 0) {
            currentTokenID = phygitalToRewardId[phygitalcontractAddr][tokenId];
        } else {
            Counter++;
            currentTokenID = Counter;
        }
        _mint(_msgSender(), currentTokenID, amount, data);
        _tokenURIs[currentTokenID] = _uri;
        setApprovalForAll(tradeHub, true);
        emit RewardTokenCreated(currentTokenID, _msgSender(), amount, _uri);
        return currentTokenID;
    }

    /**
     * @dev Creates a new token for `to`. Its token ID will be automatically
     * assigned (and available on the emitted {IERC1155-Transfer} event), and the token
     * URI autogenerated based on the base URI passed at construction.
     *
     * Requirements:
     *
     * - the caller must have the `FLOW_CREATOR_ROLE`.
     */
    function delegateAssetCreation(
        address phygitalcontractAddr,
        address creator,
        uint256 tokenId,
        uint256 amount,
        bytes memory data,
        string memory _uri
    ) public onlyOperator returns (uint256) {
        uint256 currentTokenID;
        // We cannot just use balanceOf to create the new tokenId because tokens
        // can be burned (destroyed), so we need a separate counter.
        if (phygitalToRewardId[phygitalcontractAddr][tokenId] > 0) {
            currentTokenID = phygitalToRewardId[phygitalcontractAddr][tokenId];
        } else {
            Counter++;
            currentTokenID = Counter;
        }
        _mint(creator, currentTokenID, amount, data);
        _tokenURIs[currentTokenID] = _uri;
        setApprovalForAll(tradeHub, true);
        emit RewardTokenCreated(currentTokenID, _msgSender(), amount, _uri);
        return currentTokenID;
    }

    /**
     * @notice Burns `tokenId`. See {ERC721-_burn}.
     *
     * @dev Requirements:
     *
     * - The caller must own `tokenId` or be an approved operator.
     */
    function destroyAsset(uint256 tokenId, uint256 amount) public {
        require(
            balanceOf(_msgSender(), tokenId) == amount,
            "RewardToken: Caller is not token owner or approved"
        );
        _burn(_msgSender(), tokenId, amount);
        emit RewardTokenDestroyed(tokenId, _msgSender());
    }

    /// @dev  ONLY Operator can set the Base URI
    function setURI(string memory newuri) external onlyOperator {
        _setURI(newuri);
    }

    /** Getter Functions **/

    /// @dev Returns the Uniform Resource Identifier (URI) for `tokenId` token.
    function uri(
        uint256 tokenId
    ) public view virtual override returns (string memory) {
        return _tokenURIs[tokenId];
    }

    /**
     * @dev See {IERC165-supportsInterface}.
     */
    function supportsInterface(
        bytes4 interfaceId
    ) public view virtual override(ERC1155) returns (bool) {
        return super.supportsInterface(interfaceId);
    }
}
